### ISSUE TITLE
snap install mc-server-installer not working

### ISSUE THREAD

**Issue by bwoah** [kz6fittycent/mc-server-installer#5] opened 2020-10-07 03:02 UTC
'Snap install mc-server-installer' fails.  Can only use 'snap run mc-server-installer' (one of the development commands).  

The server never finishes installing (it gets stuck at 94% in the progress display).  Using the 'snap run' command means that nothing gets created in ~/snap, though there a playable server is running (presumably in RAM?)

I am just a hobbyist, not a developer.  Trying to set up mc server for my 7-year old.  Let me know if you need additional information. THANK YOU!

**Comment by kz6fittycent** [comment] 2020-10-07 14:22
Hi @bwoah, sorry you're having this trouble. Just a couple of quick questions:

- Which distro are you running?
- Which version of the snap are you currently running? Run `snap info mc-server-installer`
- Which version of `snapd` are you running? Run `snap --version`

Note that Centos and RHEL don't do a good job at all of supporting snaps. Any snap I've installed on either distro requires running it with `snap run snapname`

If you're on either of those, I don't have any good news for you.

**Comment by bwoah** [comment] 2020-10-07 16:08
Thanks for your quick response!

On Ubuntu 20.04
The version is stable 7.1 2020-09-20
snapd   2.46.1+20.04

**Comment by kz6fittycent** [comment] 2020-10-07 16:14
Wow, now I'm confused. I'm running 20.04 and using the snap on my own server. 

Okay, several questions:

1. Did you choose option 1 to download the `.jar`?
2. Did you choose option 2 to agree to the EULA?
3. Did you choose one of the run options (e.g. #6 for 6GB of RAM)?

Do you mind pasting the output into this issue when you run `snap run mc-server-installer`?

**Comment by bwoah** [comment] 2020-10-07 18:20
Yes, I started with option 1.  

When I clicked on option 2 to agree to the EULA, it seemed to run through some sort of installation (probably from the .jar?) and stalled out at 94% and hung there.  When I clicked on cancel, it said I had agreed to the EULA and sent me back to the options menu.

I then chose option 3 and switched to creative mode.

Finally, I chose option 4 (2 GB of RAM) and again saw the same installation (text showing what was being installed and % progress) that I was when clicking on option 2 for the EULA.  It again stalled out at 94%.

FYI: After several tries (getting the same results each time) I checked ~/snap to confirm that nothing was being created there.  I then connected to my server again via a tmux session and mosh connection, ran through options 1-4, and then detached from this session.  Currently my son has a playable server, though I warned him that nothing was being saved!

**Comment by kz6fittycent** [comment] 2020-10-07 18:47
it looks like it's failing to download the `.jar` from Mojang for some reason. Let me take a look at things on the backend and see if there's something that's wrong. I just can't duplicate your issue - just installed the snap on Pop! and ran it, server started right up and all is well.

**Comment by kz6fittycent** [comment] 2020-10-07 19:15
Trying to figure out why it's not working for you, this is where I'm at on attempt 3:

```
Starting server with 2GB of RAM...

[14:13:00] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[14:13:01] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:13:01] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:13:01] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:13:01] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:13:01] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:13:01] [main/INFO]: Reloading ResourceManager: Default
[14:13:02] [Worker-Main-14/INFO]: Loaded 7 recipes
[14:13:03] [Worker-Main-14/INFO]: Loaded 927 advancements
[14:13:04] [Server thread/INFO]: Starting minecraft server version 1.16.3
[14:13:04] [Server thread/INFO]: Loading properties
[14:13:04] [Server thread/INFO]: Default game type: SURVIVAL
[14:13:04] [Server thread/INFO]: Generating keypair
[14:13:05] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:13:05] [Server thread/INFO]: Using epoll channel type
[14:13:05] [Server thread/INFO]: Preparing level "world"
[14:13:12] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:13:13] [Worker-Main-12/INFO]: Preparing spawn area: 0%
[14:13:13] [Worker-Main-18/INFO]: Preparing spawn area: 0%
[14:13:13] [Worker-Main-18/INFO]: Preparing spawn area: 0%
[14:13:14] [Worker-Main-18/INFO]: Preparing spawn area: 0%
[14:13:14] [Worker-Main-12/INFO]: Preparing spawn area: 1%
[14:13:15] [Worker-Main-18/INFO]: Preparing spawn area: 1%
[14:13:15] [Worker-Main-10/INFO]: Preparing spawn area: 1%
[14:13:16] [Worker-Main-13/INFO]: Preparing spawn area: 4%
[14:13:16] [Worker-Main-18/INFO]: Preparing spawn area: 6%
[14:13:17] [Worker-Main-18/INFO]: Preparing spawn area: 6%
[14:13:17] [Worker-Main-10/INFO]: Preparing spawn area: 6%
[14:13:18] [Worker-Main-10/INFO]: Preparing spawn area: 10%
[14:13:18] [Worker-Main-10/INFO]: Preparing spawn area: 10%
[14:13:19] [Worker-Main-11/INFO]: Preparing spawn area: 10%
[14:13:19] [Worker-Main-18/INFO]: Preparing spawn area: 16%
[14:13:20] [Worker-Main-9/INFO]: Preparing spawn area: 17%
[14:13:20] [Worker-Main-11/INFO]: Preparing spawn area: 18%
[14:13:21] [Worker-Main-13/INFO]: Preparing spawn area: 20%
[14:13:21] [Worker-Main-10/INFO]: Preparing spawn area: 22%
[14:13:22] [Worker-Main-18/INFO]: Preparing spawn area: 24%
[14:13:22] [Worker-Main-8/INFO]: Preparing spawn area: 25%
[14:13:23] [Worker-Main-9/INFO]: Preparing spawn area: 26%
[14:13:23] [Worker-Main-11/INFO]: Preparing spawn area: 27%
[14:13:24] [Worker-Main-18/INFO]: Preparing spawn area: 30%
[14:13:24] [Worker-Main-8/INFO]: Preparing spawn area: 32%
[14:13:25] [Worker-Main-13/INFO]: Preparing spawn area: 35%
[14:13:26] [Worker-Main-12/INFO]: Preparing spawn area: 35%
[14:13:26] [Worker-Main-10/INFO]: Preparing spawn area: 35%
[14:13:27] [Worker-Main-12/INFO]: Preparing spawn area: 43%
[14:13:27] [Worker-Main-9/INFO]: Preparing spawn area: 46%
[14:13:28] [Worker-Main-12/INFO]: Preparing spawn area: 48%
[14:13:28] [Worker-Main-12/INFO]: Preparing spawn area: 51%
[14:13:29] [Worker-Main-9/INFO]: Preparing spawn area: 54%
[14:13:29] [Worker-Main-10/INFO]: Preparing spawn area: 56%
[14:13:29] [Worker-Main-10/INFO]: Preparing spawn area: 57%
[14:13:31] [Worker-Main-18/INFO]: Preparing spawn area: 59%
[14:13:31] [Worker-Main-12/INFO]: Preparing spawn area: 59%
[14:13:31] [Worker-Main-12/INFO]: Preparing spawn area: 59%
[14:13:32] [Worker-Main-10/INFO]: Preparing spawn area: 67%
[14:13:32] [Worker-Main-8/INFO]: Preparing spawn area: 67%
[14:13:32] [Worker-Main-18/INFO]: Preparing spawn area: 72%
[14:13:33] [Worker-Main-11/INFO]: Preparing spawn area: 78%
[14:13:33] [Worker-Main-11/INFO]: Preparing spawn area: 83%
[14:13:34] [Worker-Main-11/INFO]: Preparing spawn area: 88%
[14:13:34] [Worker-Main-18/INFO]: Preparing spawn area: 93%
[14:13:35] [Worker-Main-9/INFO]: Preparing spawn area: 99%
[14:13:35] [Server thread/INFO]: Time elapsed: 22568 ms
[14:13:35] [Server thread/INFO]: Done (30.032s)! For help, type "help"
```

**Comment by kz6fittycent** [comment] 2020-10-07 19:18
Can you tell me a little about your hardware? 

Processor:
RAM: 
Drive space:

**Comment by bwoah** [comment] 2020-10-07 20:14
Does info from neofecth get you what you need?
  
OS: Ubuntu 20.04.1 LTS x86_64
Host: Meerkat meer1
Kernel: 5.4.0-48-generic
Uptime: 2 days, 15 hours, 46 mins
Packages: 613 (dpkg), 9 (snap)
Shell: bash 5.0.17
Resolution: 3840x2160
Terminal: /dev/pts/0
CPU: Intel i5-5250U (4) @ 2.700GHz
GPU: Intel HD Graphics 6000
Memory: 6090MiB / 15900MiB

**Comment by bwoah** [comment] 2020-10-07 20:18
My son said I could kill running minecraft server.  ;  )

Here's what I got this time when running option 4:

t='https://sessionserver.mojang.com', name='PROD'
[20:17:55] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:17:55] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:17:55] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:17:55] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:17:55] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:17:55] [main/INFO]: Reloading ResourceManager: Default
[20:17:56] [Worker-Main-4/INFO]: Loaded 7 recipes
[20:17:57] [Worker-Main-4/INFO]: Loaded 927 advancements
[20:17:59] [Server thread/INFO]: Starting minecraft server version 1.16.3
[20:17:59] [Server thread/INFO]: Loading properties
[20:17:59] [Server thread/INFO]: Default game type: CREATIVE
[20:17:59] [Server thread/INFO]: Generating keypair
[20:18:00] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:18:00] [Server thread/INFO]: Using epoll channel type
[20:18:00] [Server thread/INFO]: Preparing level "world"
[20:18:00] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:18:03] [Server thread/INFO]: Preparing spawn area: 0%
[20:18:03] [Server thread/INFO]: Preparing spawn area: 0%
[20:18:03] [Server thread/INFO]: Preparing spawn area: 0%
[20:18:03] [Server thread/INFO]: Preparing spawn area: 0%
[20:18:03] [Server thread/INFO]: Preparing spawn area: 0%
[20:18:03] [Server thread/INFO]: Preparing spawn area: 0%
[20:18:03] [Server thread/INFO]: Preparing spawn area: 4%
[20:18:04] [Server thread/INFO]: Time elapsed: 3729 ms
[20:18:04] [Server thread/INFO]: Done (3.968s)! For help, type "help"
[20:18:07] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2368ms or 47 ticks behind

**Comment by kz6fittycent** [comment] 2020-10-07 20:20
Okay, can you take a look and paste the output from the following command here?

`snap run --strace mc-server-installer`

This will start printing any errors - it might be a LOT of output, if so, run this command:

`snap run --strace mc-server-installer 2>&1 | tee mc-server-installer-strace.txt`

Then attach the text file to this issue (drag and drop)

**Comment by bwoah** [comment] 2020-10-07 20:28
[mc-server-installer-strace.txt](https://github.com/kz6fittycent/mc-server-installer/files/5343618/mc-server-installer-strace.txt)

My son is avidly watching this whole exchange and is thrilled.  Thanks for looking at this.

**Comment by kz6fittycent** [comment] 2020-10-07 21:15
### Okay, if you guys are ready, you're going to put on your "developer" hats!

You'll need to install `gdb` - `sudo apt install gdb`

Then you'll run: `snap run --experimental-gdbserver mc-server-installer`

Your terminal will then print something like the following:

```
Welcome to "snap run --gdbserver".
You are right before your application is run.
Please open a different terminal and run:

gdb -ex="target remote :33963" -ex=continue -ex="signal SIGCONT"
(gdb) continue

or use your favorite gdb frontend and connect to :33963


THIS OPTION IS EXPERIMENTAL

Welcome to `snap run --gdb`.
You are right before your application is execed():
- set any options you may need
- (optionally) set a breakpoint in 'main'
- use 'cont' to start
```

Then, you'll open up another terminal window and paste in the part that says: 

`gdb -ex="target remote :33963" -ex=continue -ex="signal SIGCONT"` <- that "target remote" number will be different for you.

Then, you'll see the program execute each stage as you hit "Enter" - `gdb` says "RET"

What we're looking for is `SIGTERM`. If we see `SIGCONT`, things are working. For me, I get `SIGCONT` all the down because it's working for me. 

If you *don't* see `SIGTERM`, the snap is working as intended and there's _maybe_ a network issue? 

As basic as this sounds, we can try removing the snap and reinstalling the `edge` version. Not refreshing, but actually removing and then installing the latest version (still 7.1). 

`sudo snap install --edge mc-server-installer`

**Comment by bwoah** [comment] 2020-10-08 03:28
Thank you for all of your help.  My son helped type in some of the commands and I appreciate you taking the time to write clear instructions.

No luck!  We ran the gdb server in one terminal and used gdb -ex="target remote . . ." in another terminal.  Did not see SIGTERM.

I uninstalled mc-server-installer and installed the edge version.  It still stalled out during the EULA signing process:

```
[02:59:22] [Server thread/INFO]: Preparing spawn area: 97%
[02:59:22] [Server thread/INFO]: Preparing spawn area: 97%
[02:59:22] [Server thread/INFO]: Time elapsed: 34306 ms
[02:59:22] [Server thread/INFO]: Done (34.604s)! For help, type "help"
[02:59:24] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2553ms or 51 ticks behind
```

It occurred to me to install mc-server-install on my laptop, running Pop OS 20.04.  It seemed to install just fine, though I did not test the actual server.  The EULA process was completed in seconds and was different than when attempting on my server.  On the Ubuntu server it seems like it is trying to install and set up the .jar but on Pop OS gave the following output:

```
Agreeing to the EULA...
[20:10:35] [main/ERROR]: Failed to load properties from file: server.properties
[20:10:35] [main/WARN]: Failed to load eula.txt
[20:10:35] [main/INFO]: You need to agree to the EULA in order to run the server. Go to eula.txt for more info.


Done!

press RETURN for menu
```

One thing I noted: there still wasn't a directory in ~/snap for mc-server.

I am happy to try something else if you have any suggestions.  And I can run the server install again on my laptop to confirm that the server is working.

Thanks again!

**Comment by kz6fittycent** [comment] 2020-10-08 14:37
I'm at a loss. I'm really sorry that I can't duplicate these issues. As for the directory not being created, that's really weird and might indicate an issue with `snapd` - in fact, I'm thinking that's the problem altogether but I can't understand why. 

Are other snaps working as intended?

**Comment by bwoah** [comment] 2020-10-10 22:14
Thank you!  I really appreciate your help.  I'll take a look at the mc-installer snap but was really wanting to run this from a container.

Thanks for the suggestion for the cornyjokes snap.  My son loves typing things into cowsay, so he will love cornyjokes!

**Comment by kz6fittycent** [comment] 2020-10-12 22:42
@bwoah I just did a fresh install on another Ubuntu server of mine (20.04) and it's working just fine. I'm wondering if there's something different in our baselines that's to blame. What permissions do you have set for `/home/user`? Or specifically on `/home/user/snap/`?

**Comment by kz6fittycent** [comment] 2020-10-16 23:29
I'll go ahead and close this on 20 OCT 2020 if I don't hear back from you. Sorry again that this didn't work out for you.

**Closed** 2020-10-20 23:44 UTC
